apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: my-cluster
  # region: us-east-1

nodeGroups:
  - name: my-nodes
    instanceType: t3.small
    desiredCapacity: 1
    minSize: 1
    maxSize: 2